POST http://localhost:3003/api/blogit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcnR0aSIsImlkIjoiNmEwMTkwMDJjMTE1NDMwNmZjYTk1MDBhIiwiaWF0IjoxNzc4NDg3MzA5fQ.zu62STbXnDP1iHJxu1VAcp6xU4e9ByJymjulooIqpUc

{
    "title": "pöö",
    "author": "1345",
    "url": "http://pöö.com", 
    "likes": 3,
    "userId": "6a0186778432626bfcd87a68"
}