POST http://localhost:3003/api/blogit
Content-Type: application/json

{
    "title": "pöö",
    "author": "1345",
    "url": "http://pöö.com", 
    "likes": 3,
    "userId": "6a0186778432626bfcd87a68"
}