POST http://localhost:3003/api/blogit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvcGkiLCJpZCI6IjZhMDIwMjA5NDYwMTBlNGVlZjAzOGRjYiIsImlhdCI6MTc3ODUxNjUyNH0.XsNmf-w3fNtV2Mh7gKt5wgBbwvx2DFlFZ8BTiJwU-zs

{
    "title": "jepu",
    "author": "134sfeg5",
    "url": "http://pää.com", 
    "likes": 3,
    "userId": "6a01921f37f91ab8cb9b52a8"
}